<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZULxbjy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZULxbjy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZULxbjy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZULxbjy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZULxbjy\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZULxbjy',
    'container.build_id' => '5f02260c',
    'container.build_time' => 1602086254,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZULxbjy');
