<?php

namespace ContainerRY8MZn7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssociation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uVKVO.j.App\Entity\Association' shared service.
     *
     * @return \App\Entity\Association
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uVKVO.j": it references class "App\\Entity\\Association" but no such service exists.');
    }
}
