<?php

namespace ContainerRY8MZn7;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UVKVO_JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uVKVO.j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uVKVO.j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'association' => ['privates', '.errored..service_locator.uVKVO.j.App\\Entity\\Association', NULL, 'Cannot autowire service ".service_locator.uVKVO.j": it references class "App\\Entity\\Association" but no such service exists.'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'association' => 'App\\Entity\\Association',
            'slugger' => '?',
        ]);
    }
}
